### ISSUE TITLE
Uncarried Coins aren't Tracked in Party Inventory

### ISSUE THREAD

**Issue by bmos** [bmos/FG-PFRPG-TotalEncumbrance#4]
Should they be?

**Comment by crusopaul** [comment]
Yeah that's kind of tricky. I remember reading about a feature request for coin weight that specifically was asking for a non-carried representation of putting coins in something like a bank. It might be worth adding an extra field for party-carried coins for which we could equally distribute/penalize amongst party PCs. The node for this element would/should have to be PC-agnostic and above the PC DB node.

**Comment by bmos** [comment]
That actually exists on the party sheet already. "Party Funds" which has a button to equally distribute the wealth when desired.

**Comment by crusopaul** [comment]
Love it. That may also be relatively straightforward to implement then. Because I love a good rounding issue, there's some additional input I have on the matter of arbitrarily assigning round-off to PC's coin weights. We'd ultimately want to assign round-off to PCs based on a deterministic sorting algorithm rather than a random PC assignment as PC equipment / STR changes / inventorylist child updates would re-randomize round-off assignment. In other words, mid-battle inventory changes from a disengaged PC would add penalties to PC who may not be aware of the other PC's application interaction (during a spell cast / skill check / or w/e) if that makes sense?

**Comment by bmos** [comment]
You'll love this: It leaves any coins that can't be distributed behind.

**Comment by crusopaul** [comment]
In response to "You'll love this: It leaves any coins that can't be distributed behind", askdfalskjdfl;askjdf

**Comment by bmos** [comment]
Planned coin weight re-implementation will avoid this issue altogether.
